
import Fastify, { FastifyInstance } from 'fastify'
import fastifySwagger from "fastify-swagger";
import { routes } from "./routes";
import SwapDB from './SwapDB';
import { EmerisDEXInfo } from '@emeris/types';
import { OsmosisSource } from './sources/osmosis';
import DenomDB from './DenomDB';
import {SifchainSource} from "./sources/sifchain";
import {JunoswapSource} from "./sources/junoswap";

const server: FastifyInstance = Fastify({})



server.register(fastifySwagger, {
  routePrefix: "/apidocs",
  exposeRoute: true,
  swagger: {
    info: {
      title: "Emeris DEX Info API",
      description:
        "RESTful API with Node.js, Fastify, TypeScript and autogenerated Swagger for accessing DEX information",
      version: "1.0.0",
    },
    externalDocs: {
      url: "https://swagger.io",
      description: "Find more info here",
    },
    consumes: ["application/json"],
    produces: ["application/json"],
  },
});


const start = async () => {

  routes.forEach((route) => {
    route.add(server);
  });
  await DenomDB.isLoaded();
  SwapDB.setSources([
      EmerisDEXInfo.DEX.Osmosis,
      EmerisDEXInfo.DEX.Sifchain,
      EmerisDEXInfo.DEX.Junoswap,
  ]);
  const osmo = new OsmosisSource('https://lcd-osmosis.keplr.app', true, 10000);
  osmo.on('swaps', (data) => { SwapDB.update(EmerisDEXInfo.DEX.Osmosis, data) });
  //
  // const sif = new SifchainSource('https://api.sifchain.finance/clp/getPools', true, 10000);
  // sif.on('swaps', (data) => { SwapDB.update(EmerisDEXInfo.DEX.Sifchain, data) });

  const juno = new JunoswapSource('https://raw.githubusercontent.com/CosmosContracts/junoswap-asset-list/main/pools_list.json', true, 10000);
  juno.on('swaps', (data) => { SwapDB.update(EmerisDEXInfo.DEX.Junoswap, data) });

  try {
    await server.listen(8080,'0.0.0.0');
    server.swagger();
  } catch (err) {
    console.log(err)
    process.exit(1)
  }
}
start()
